### ISSUE TITLE
AGUILAR GARAY AARON

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/redes#2]
Entegar código de programas

**Comment by IoTeacher** [comment]
@AaronDrumCore

**Comment by AaronDrumCore** [comment]
Profesor ya subi el codigo con mi user "AaronDrumCore", de las practicas
que elabore, en estos dias subo las capacitaciones que faltan a Slack

2016-11-30 15:43 GMT-08:00 René Solis <notifications@github.com>:

**Comment by IoTeacher** [comment]
Ok prox semestre creo que no dejare que suban código a Slack. Gracias por hacerme la observación y mejorar mas este curso.

**Comment by AaronDrumCore** [comment]
Se refiere ami? yo solo subí las capacitaciones

**Comment by AaronDrumCore** [comment]
A slack, el código lo subí a git

**Comment by jclardizabal** [comment]
Profesor René, aún no me ha puesto calificación en las capacitaciones de la
unidad 2 y 3 y los certificados ya están en la plataforma de slack.com y
Tijuana.Education

**Comment by AaronDrumCore** [comment]
Yo tampoco tengo calificación aun

**Comment by IoTeacher** [comment]
Listo.
