### ISSUE TITLE
Server Friday Pizza

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/redes#3]
Convivio del 14 de febrero, Server Friday
![maxresdefault](https://cloud.githubusercontent.com/assets/2523851/12862257/3a86996e-cc6a-11e5-8034-82350ebc7383.jpg)

@tectijuana/redes Como la ven? Se pueden organizar, llevo 5 pizzas + mesa

Veamos que bien son para socializarse

**Comment by Mikooo** [comment]
:+1:  :D

**Comment by CarmenEsqueda** [comment]
PIzza!! :3

**Comment by Mikooo** [comment]
:+1:  :DD

**Comment by scarlettc** [comment]
Llevo un paquete de vasos 😆

**Comment by 4dri4n** [comment]
Muy bien llevare platos y 1 soda de 2 lts y mi NOS funcionando

**Comment by omar194** [comment]
llevo vasos

**Comment by sarita23** [comment]
Llevare una soda de 2Lts :3

**Comment by alonsoitt** [comment]
**Yo espero llegar temprano y llevare servilletas n.n**

**Comment by PriscillaE** [comment]
Una soda de 3lts

**Comment by CarmenEsqueda** [comment]
Pues yo tengo muchos vasos y plato, pero y las pizzas como...

**Comment by danielopez25** [comment]
Yo llevo una pizza

2016-02-11 21:49 GMT-08:00, Carrmen Esqueda <notifications@github.com>:

**Comment by andresmichel** [comment]
Yo llevo más soda.

**Comment by IoTeacher** [comment]
De mi parte todo listo, llevo una Mesa plegable y 5 pizzas.


![img_0001](https://cloud.githubusercontent.com/assets/2523851/13019834/97a522fc-d186-11e5-958e-692212bb5c6c.jpg)

**Comment by IoTeacher** [comment]
![estudiantes exitosos 2](https://cloud.githubusercontent.com/assets/2523851/13023755/bcd17426-d1a0-11e5-98ed-82d9c3a8703b.jpg)


Como la vieron que falto que sobro que opinión hay ... expresarse constructivamente.

**Comment by 4dri4n** [comment]
Me pareció muy bien ,siento que si falto un poco mas de pizza pero para la siguiente ya sabemos mas o menos cuanto , muchas gracias profe Rene solis

**Comment by CarmenEsqueda** [comment]
Me pareció bien, creo que falto pizza :3 pero fue entretenido 
estaría padre repetirlo

**Comment by scarlettc** [comment]
La proxima podriamos llevar en grupos de 3 o 4 una pizza :D

**Comment by IoTeacher** [comment]
Claro aqui lo importante es que se sientan agusto y aparte fue para que se relajaran por este 14 de febrero, es una carrera muy estresante y demandante por los tiempos, y claro si falto mas organización como Uds. dicen pero lo importante que  @tectijuana/redes procuran estar unidos como grupo/generación e invitar a los demas a asociarse con uds.
